### ISSUE TITLE
No Touch control available

### ISSUE THREAD

**Issue by ghost** [htruong/crankshaft#356] opened 2019-06-29 16:58 UTC
When I start cranckshaft it works fine, I can do everything until I plug in my phone. Once Android Auto starts, I lose touch control, I can't do anything. Please, can someone give me a hand with this thing? I don't really know why is happening, and how to solve :(

**Comment by danielcrex** [comment] 2019-06-30 00:35
same thing for me

**Comment by iofirag** [comment] 2019-06-30 06:49
Seems that you had faces this already open issue https://github.com/opencardev/crankshaft/issues/352

**Comment by hawkeyexp** [comment] 2019-07-01 15:22
Duplicate of #352

**Closed as completed by hawkeyexp** 2019-07-01 15:22 UTC
Labels: duplicate, crankshaft-ng
