### ISSUE TITLE
FM radio integration.

### ISSUE THREAD

**Issue by bob5731** [htruong/crankshaft#398] opened 2019-11-16 21:36 UTC
Has anybody in a greater than FM tuner to crankshaft in raspberry pi 3? I'm looking for a plug and play solution. Since I cannot solder due to my hand shaking.

**Comment by abraha2d** [comment] 2019-11-17 19:46
I think #384 is the closest we have. Pretty sure no soldering is necessary, just plugging in a USB rtl_sdr.

**Comment by bob5731** [comment] 2019-11-18 21:38
can I get step by step?

**Comment by abraha2d** [comment] 2019-11-19 02:49
It looks like there's already one on that issue: https://github.com/opencardev/crankshaft/issues/384#issuecomment-544168809
(I have not tested it personally, since I do not have the necessary hardware)
Closing this issue as a duplicate of the other one.

**Closed as completed by abraha2d** 2019-11-19 02:49 UTC
