### ISSUE TITLE
[BUG] Unable to connect to AA WiFi

### ISSUE THREAD

**Issue by Codehhh** [htruong/crankshaft#273] opened 2018-12-09 22:55 UTC
- What phone do you have?
Pixel 2 XL
- What OS version?
9
- What crankshaft version?
E9028A9 (2018-12-07)
- Steps to reproduce the bug, if you're planning to report a bug. Please indicate whether the bug is always repoducible.
Attempt to start Android Auto through WiFi

- Please provide any further information that you might find helpful if available.
WiFi connection worked previously.

- Starting with pre4: Boot into dev mode (can be selected in settings).
  Reproduce the possible bug. Create the debug logs by pushing the grey button on bottom of screen.
  Add the created file (/boot/debug.zip) to the issue.
[debug.zip](https://github.com/opencardev/crankshaft/files/2661101/debug.zip)

**Comment by hawkeyexp** [comment] 2018-12-12 01:55
I can only reproduce the behaviour if started in normal mode and manually switched to hotspot than tried to connect... strange but ...
Try enable hotspot with system start and try again - this way it was working for me...

**Comment by miro279** [comment] 2018-12-14 10:29
Hi, I just updated to Pre15 and have the same problems since than. Most times I try to connect to the phone via wifi the GUI of crankshaft crahes, other times noting at all happens. In some seldom times it just works. Crankshaft is started in hotspot mode.
I'm on a Leeco Pro Elite with latest linageOS, latest version of Android Auto. Pre14 was working with wifi no problems.

**Comment by hawkeyexp** [comment] 2018-12-14 12:36
AA Wifi is a bi... :-) I'm working on it...

**Comment by miro279** [comment] 2018-12-14 13:52
I believe you ;-) anyway, if I can hell to Debüt, please tell me how. Would my logs help you? Funny it was really stabil in Pre14.. Thanks for your work!!!

**Comment by miro279** [comment] 2018-12-14 15:06
My logs..
[debug.zip](https://github.com/opencardev/crankshaft/files/2680524/debug.zip)

**Comment by hawkeyexp** [comment] 2018-12-14 15:15
Thx for the logs but not needed in this case - it's caused inside openauto and outputs only a segfault :-) But seems to be fixed now (hopefully).

**Comment by miro279** [comment] 2018-12-14 15:19
Yes, I'm taking a look at the log myself but the only message I find is that crankshaft crashed.. Do you release a new version just now?

**Comment by hawkeyexp** [comment] 2018-12-14 15:35
I think no new release today cause i wan't to check it a bit more to prevent from effects like in Pre15.

**Comment by miro279** [comment] 2018-12-14 15:36
Standing by to test ;-)

**Closed as completed** 2018-12-21 01:40 UTC
Labels: bug, crankshaft-ng, Fixed/Released

**Comment by Codehhh** [comment] 2018-12-24 18:57
Confirmed fixed, thanks!
