### ISSUE TITLE
Wireless mode - possible to use phone hotspot?

### ISSUE THREAD

**Issue by yusijs** [htruong/crankshaft#250] opened 2018-10-13 20:45 UTC
Hi!

So currently we need to use the Pi as a hotspot, and connect our phone to it. However, this  can be a problem, since not everyone can use both wifi + mobile data (myself included). As far as OpenAuto goes, I believe the only rule is that the devices needs to be on the same network, which in turn should mean it's a possibility to use your phone as a hotspot, and in turn connect the Pi to it?

As far as I'm able to tell, the only blocker for this is that Wifi is disabled when not in dev mode - if so, is it possible to have Wifi enabled in client mode?

I have another interest in this as well - I recently wrote a simple internet radio application for myself that I wanted to install on the headunit that I can launch without my phone connected, but to do this, I need an internet connection. An idea I had was to install a usb 4g modem in my car, which would allow me to listen to the radio without my phone connected.

Thanks for your time!

**Comment by parkerlreed** [comment] 2018-10-13 20:59
Yes, phone as hotspot works just fine. Use the phone's address which is usually 192.168.42.1 (it'll be the default route that shows up on the Pi)

**Comment by yusijs** [comment] 2018-10-13 21:19
Question was more on how the connection to the phone was established - is it just to change the SSID and password in the env file now, and it'll work outside of dev mode?

**Comment by hawkeyexp** [comment] 2018-10-14 01:26
Wait until next release possible next week - some network related reworks will come up which opens more ways to use...
But a side node: cs as client won't be official supported cause it's not the default usecase for mainstream users also not google's default way.

**Comment by inspector71** [comment] 2018-10-14 10:42
@yusijs What phone are you using? Android version? I'm curious about which phones, perhaps OEMs, disable concurrent mobile and WiFi. I've owned Samsung and ASUS Android phones and IIRC, Samsung didn't block concurrent networking on my old Galaxy S2 and my current ASUS does not either.

**Comment by hawkeyexp** [comment] 2018-10-14 14:09
@inspector71 it's try and error until a device has android 9 which should official bring aa wifi to oem devices. Official supported are only google phones if firmware is lower than android 9 by google.

**Comment by yusijs** [comment] 2018-10-17 18:17
@inspector71 Huawei Mate 10 Pro. I have the setting available via developer menu (mobile data always on), but it's not used when the wifi doesn't have an internet connection.

**Comment by inspector71** [comment] 2018-10-18 01:42
Wow, that sucks. I hate it when software is crippled for no good reason.
That you can then intelligently opt out of that crippling but the system
doesn't function as it should with that override in place, really blows.

Is your phone essentially running it's 'native' Hauwei firmware? What
Android version are you running?

**Comment by yusijs** [comment] 2018-10-18 06:59
Yeah, stock Emui, android 8. I decided to get openauto pro, as it allows me to easily use my phone as the hotspot :)

**Comment by inspector71** [comment] 2018-10-18 08:18
OpenAuto Pro is an interesting one. I didn't know it existed and then found
out about it and wondered if Crankshaft would always be limited in
comparison. Then forgot about it again.

Are you using OpenAuto Pro within Crankshaft or is it a completely separate
distribution?

**Comment by yusijs** [comment] 2018-10-18 10:24
Separate SD cards. Crankshaft is more plug and play, but more of a hassle to customize. Openauto Pro is an application running on top of raspbian, so I have direct access to the underlying system w/o booting to dev mode.

I like Crankshaft better in general use (easy to add rtc, io pins etc), but I use openauto more now as it's easier to access the underlying system, and it's less opininated :-) 

YMMW!

**Comment by inspector71** [comment] 2018-10-18 11:27
> 
> 
> Separate SD cards. Crankshaft is more plug and play, but more of a hassle to customize. Openauto Pro is an application running on top of raspbian, so I have direct access to the underlying system w/o booting to dev mode.
> 
> I like Crankshaft better in general use (easy to add rtc, io pins etc), but I use openauto more now as it's easier to access the underlying system, and it's less opininated :-)
> 
> YMMW!

Thanks for the info. Interesting stuff. Curious what you mean about opinionated but maybe that's for another place / thread.

**Comment by hawkeyexp** [comment] 2018-10-18 13:09
I think we should close this issue cause it's more a discussion than an issue - you are welcome to use reddit for discussions.

**Closed as completed by hawkeyexp** 2018-10-18 13:09 UTC

**Comment by inspector71** [comment] 2018-10-18 13:33
> 
> 
> @inspector71 it's try and error until a device has android 9 which should official bring aa wifi to oem devices. Official supported are only google phones if firmware is lower than android 9 by google.

@hawkeyexp yeah fair enough. Another way of saying "trial and error" is "crowdsourced knowledge" :) Would be great if all CS users could help us generate a list of devices that have, or do not have, this wifi / mobile data concurrency issue.

**Comment by hawkeyexp** [comment] 2018-10-18 14:10
@inspector71 for me a list feels useless cause 8.x is not official supported for aa wifi and it can change every time with every firmware update etc.

**Comment by yusijs** [comment] 2018-10-18 16:15
Theres also the hw support issue here somewhere - I wrote down that it worked w/o internet at least.

Also @inspector71, by opinionated I mean that the creator(s) is limiting parts of the system. That's not a bad thing - it often makes the system easier to work with for endusers, but the downside is that it's limiting those of us who want a more customized solution (by creating barriers to do certain things, such as this issue). 

Again - not a bad thing, just a matter of preference. :-)

**Comment by hawkeyexp** [comment] 2018-10-18 16:33
The system is NOT limited - you can work and edit on all parts - also the source is open - so nobody is  limited to fork it and customize it. And the not used wifi in the past was also no limit - the only supported devices was the pixel ones and this limit is starting to be reduced with android pie and was not caused by cs.

**Comment by inspector71** [comment] 2018-10-19 13:14
I expect 'limited' might be a reference to the safety approach you've taken
Hawkeye. That was a hard limit imposed on potential users. That's not too
day the reasoning for that limit was unreasonable. But let's not pretend
the limit isn't there, it is.

"Limited" is not necessarily a criticism. Just an observation. Software
developers make choices all the time. Those choices can become limits on
users. Forks are not necessarily a solution as they can take what momentum
a project has generated and spread the resources behind that momentum too
thinly. The original project suffers and the offshoot project never quite
takes off.

A lot of open source software is not actually very democratic. People get
drawn to it and contribute however they can but unless there's an open,
balanced system in place to debate and choose the direction the project
moves in, there's a lack of democratic process. A good example is OpenELEC
versus LibreELEC.
